name: Node.js Build and Upload Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Change directory to src and install dependencies
        run: |
          cd src
          npm install

      - name: Build with Grunt
        run: |
          cd src
          npx grunt build

      - name: Find build output files
        id: find_files
        run: |
          cd src
          mkdir -p ../output-artifacts
          # Find all files modified in the last 10 minutes as likely build outputs
          find . -type f -mmin -10 -print > ../output-artifacts/list.txt
          # Copy those files to a flat structure in ../output-artifacts
          while IFS= read -r f; do
            if [ -f "$f" ]; then
              mkdir -p ../output-artifacts/$(dirname "$f")
              cp --parents "$f" ../output-artifacts/
            fi
          done < ../output-artifacts/list.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: output-artifacts/
          if-no-files-found: warn
